### ISSUE TITLE
Manifest is ignored when opening the link in Firefox

### ISSUE THREAD

**Issue by dscho** [gr2m/register-github-app#6]
### Please avoid duplicates

- [x] I checked [all open bugs](https://github.com/gr2m/register-github-app/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

npx register-github-app-cli

### Please select the environment(s) that are relevant to your bug report

- [x] Browsers
- [ ] Node
- [ ] Deno

### Versions

Using `npx`, expect `register-github-app` to be at the latest version; Firefox v125.0.1

### What happened?

With Firefox v125.0.1, the manifest seems to be ignored, and a completely empty form is shown, the top looks like this:

![Image](https://github.com/gr2m/register-github-app/assets/127790/73a1cfaf-4783-45b4-b9e1-caa9ba711435)

When I open the link in Edge instead, it works as expected, the form shows only the app's name.

### Would you be interested in contributing a fix?

- [x] yes

**Comment by gr2m** [comment]
You need to set the path to the manifest file using `--manifest`

e.g.

```
npx register-github-app-cli --manifest app.yml
```

I was not able to reproduce any problem using latest Firefox on Mac OS

**Comment by dscho** [comment]
With Firefox 125.0.3:

![Image](https://github.com/gr2m/register-github-app/assets/127790/e2ee2200-c306-460d-9a28-d81ba386c623)

https://github.com/gr2m/register-github-app/assets/127790/2ed8ef52-9f8f-4b9d-ac9f-f51f6bcfee88

**Comment by gr2m** [comment]
thanks can you please share the contents of `app.yml`?

**Comment by dscho** [comment]
> thanks can you please share the contents of `app.yml`?

@gr2m of course!

```yml
name: gr2m-reproducer
url: https://github.com/apps/gr2m-reproducer
hook_attributes:
  url: https://gr2m-reproducer-github-app.azurewebsites.net/api/Reproducer
public: false
default_permissions:
  actions: read
  administration: read
  checks: read
  contents: read
  deployments: read
  emails: read
  environments: read
  issues: read
  metadata: read
  pull_requests: read
```
